In [11]:
#import libraries
import numpy as np
import pandas as pd

In [3]:
#creating a numpy array
arr = np.array([10, 20, 30, 40, 50])
print(arr)
print("Average number:", arr.mean())

[10 20 30 40 50]
Average number: 30.0


In [4]:
#indexing
print(arr[0])
print(arr[4])
print(arr[3])
print(arr[2])
print(arr[1])
print([-3])

10
50
40
30
20
[-3]


In [7]:
#slicing
print(arr[1:4])
print(arr[::2])
print(arr[:7])
print(arr[7:])
print(arr[-1:-4])
print(arr[:])
print(arr[-4:-1])
print(arr[4:2])

[20 30 40]
[10 30 50]
[10 20 30 40 50]
[]
[]
[10 20 30 40 50]
[20 30 40]


In [12]:
#creatinng a 2D array
metrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(metrix[1,0])
print(metrix[:2, 0])
print(metrix[1, 0:2])
print(metrix[:, 2])

4
[1 4]
[4 5]
[3 6 9]


In [19]:
#convertinng 1D to 2D array
arr2 = np.arange(1, 13)
reshape = arr2.reshape(3, 4)

print("Original array:", arr2)
print("Reshape array:\n", reshape)
#flatten
flaten = reshape.flatten() 
print("1D array:", flatten)

Original array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshape array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
1D array: [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [21]:
#working with mathematical operation
arr3 = np.array([1, 2, 3, 4, 5])
arr4 = np.array([10, 20, 30, 40, 59])

print(arr3 + arr4)
print(arr3 - arr4)
print(arr3 * arr4)
print(arr3 / arr)

print("Scalar Opeation:\n ")
print(arr3 ** 2)
print(arr4 / 2)

[11 22 33 44 64]
[ -9 -18 -27 -36 -54]
[ 10  40  90 160 295]
[0.1 0.1 0.1 0.1 0.1]
Scalar Opeation:
 
[ 1  4  9 16 25]
[ 5.  10.  15.  20.  29.5]


In [5]:
#using matrix with dot product
matrix_1 = np.array([
    [1, 2],
    [3, 4]
])

matrix_2 = np.array([
    [5, 6],
    [7, 8]
])

result = np.dot(matrix_1, matrix_2)
print(result)

[[19 22]
 [43 50]]


In [7]:
#using matrix with dot product
matrix_1 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

matrix_2 = np.array([
    [10, 11, 12],
    [13, 14, 15],
    [16, 17, 18]
])

result = np.dot(matrix_1, matrix_2)
print(result)

multiply_matrix = matrix_1 * matrix_2
print(multiply_matrix)

[[ 84  90  96]
 [201 216 231]
 [318 342 366]]
[[ 10  22  36]
 [ 52  70  90]
 [112 136 162]]


In [12]:
#create fitness steps sample data
np.random.seed(42) #reproducibility
days = np.arange(1, 31)
steps = np.random.randint(3456, 12054, size=30)

data = pd.DataFrame({
    "Days": days,
    "Steps": steps
})

data

Days  Steps
0      1  10726
1      2   4316
2      3   8846
3      4   8647
4      5   9190
5      6   9721
6      7   3922
7      8   7882
8      9   9034
9     10  11778
10    11   5141
11    12   4225
12    13  10405
13    14   5889
14    15   8767
15    16   8507
16    17   9876
17    18   4640
18    19   8011
19    20   6841
20    21   9852
21    22   6014
22    23  11305
23    24   5503
24    25   6203
25    26   3645
26    27   6190
27    28   6461
28    29   8114
29    30   5355

In [13]:
#find the basic stats
step_mean = np.mean(steps)
step_median = np.median(steps)
step_min = np.min(steps)
step_max = np.max(steps)
step_std = np.std(steps)

print("Average steps count:", step_mean)
print("The median steps count:", step_median)
print("Lowest steps count:", step_min)
print("Highest steps count:", step_max)
print("Standard Deviation count:", step_std)

Average steps count: 7500.2
The median steps count: 7946.5
Lowest steps count: 3645
Highest steps count: 11778
Standard Deviation count: 2309.770715893679


In [17]:
#find the goal data person take > 10,000 steps
goal_day = np.where(steps >= 10000)[0] + 1
print(goal_day)

[ 1 10 13 23]


In [22]:
#slipt 30 days into four weeks
weeks = np.array_split(steps , 4)
week_total = [print(week.sum()) for week in weeks]
week_avg = [print(week.mean()) for week in weeks]


63250
63746
56539
41471
7906.25
7968.25
8077.0
5924.428571428572


In [27]:
lower_bound = step_mean - 2 * step_std
upper_bound = step_mean + 2 * step_std

outlier = np.where((steps < lower_bound) | (steps > upper_bound))[0] + 1
print(outlier)

[]


In [30]:
lower_bound
upper_bound

np.float64(12119.741431787359)

In [2]:
#import libraries
import numpy as np

In [16]:
#creating numpy array
arr = np.array([5, 7, 10, 2, 5, 11, 12, 4, 8])
print(arr)
#mean
print("mean =", np.mean(arr))
#median
print("Median =", np.median(arr))
#mode
counts = np.bincount(arr)
mode = np.argmax(counts)
print("Mode =",mode)
#standard deviation
print("Standard deviation =", np.std(arr))
#variance
print("Variance =", np.var(arr))

[ 5  7 10  2  5 11 12  4  8]
mean = 7.111111111111111
Median = 7.0
Mode = 5
Standard deviation = 3.212629398844658
Variance = 10.320987654320987
